apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-deployment
  labels:
    app: blogapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp
  template:
    metadata:
      labels:
        app: blogapp
      annotations:
        io.kubernetes.cri-o.TrustedSandbox: "false"
        io.kubernetes.cri.untrusted-workload: "true"
    spec:
      containers:
      - name: blogapp
        image: raravena80/blogapp:0.0.3
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: ADDR
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
